//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VCMDL.rc
//
#define IDC_CHOOSEBUT                   3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VCMDL_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDR_MODELMENU                   129
#define IDD_TABDLG_CREATE               132
#define IDD_TABDLG_MODIFY               133
#define IDD_TABDLG_BONES                134
#define IDD_TABDLG_VIEW                 135
#define IDD_TOOLDLG_SIDE                136
#define IDB_BITMAP1                     137
#define IDD_TOOLDLG_BOTTOM              138
#define IDD_EXPORTNAMINGDLG             140
#define IDD_CONFIG_KEY_PAGE             141
#define IDD_PRESSKEY_DIALOG             142
#define IDD_SKIN_MAIN_DIALOG            143
#define IDD_SKIN_TOOLDLG_SIDE           144
#define IDD_SKIN_TABDLG_MODIFY          145
#define IDD_SKIN_TOOLDLG_BOTTOM         146
#define IDR_SKINEDITMENU                147
#define IDD_PASTEVERTS_DIALOG           148
#define IDD_PASTERANGE_DIALOG           149
#define IDD_MISC_RENAME_DIALOG          150
#define IDD_GOTOFRAME_DIALOG            151
#define IDD_ADDFRAME_DIALOG             152
#define IDD_DELETEFRAMES_DIALOG         153
#define IDD_MOVEFRAMES_DIALOG           154
#define IDD_GROUNDPOS_DIALOG            155
#define IDD_CONSOLE_DIALOG              156
#define IDD_PAINT_MAIN_DIALOG           157
#define IDD_PAINT_TOOLDLG_BOTTOM        158
#define IDD_PAINT_TABDLG_PAINT          159
#define IDD_EXTRUDEDIST_DIALOG          160
#define IDC_CURSORDRAW                  161
#define IDC_CURSORDROPPER               162
#define IDC_CURSORMINUS                 163
#define IDC_CURSORMOVE                  164
#define IDC_CURSORARROW                 165
#define IDC_CURSORORIGIN                166
#define IDC_CURSORPAN                   167
#define IDC_CURSORROTATE                168
#define IDC_CURSORSCALE                 169
#define IDC_CURSORSELECTBOX             170
#define IDC_CURSORTRIANGLE              171
#define IDC_CURSORVERTEX                172
#define IDR_PAINTMENU                   173
#define IDD_GETSKINVERTSFROMMODEL       175
#define IDD_RESIZESKIN_DIALOG           176
#define IDD_INSERTNEWSKIN_DIALOG        177
#define IDD_CONFIG_DIR_PAGE             178
#define IDD_CONFIG_COLOR_PAGE           179
#define IDD_TYPEIN_POPUP                180
#define IDD_CONFIG_UNDO_PAGE            181
#define IDC_TOOLTAB                     1002
#define IDC_CREATEVERTEXBUT             1005
#define IDC_BUILDFACEBUT                1006
#define IDC_SELECTBUT                   1006
#define IDC_HIDESELECTEDBUT             1007
#define IDC_MOVEBUT                     1008
#define IDC_HIDEUNSELECTEDBUT           1008
#define IDC_ROTATEBUT                   1009
#define IDC_UNHIDEALLBUT                1009
#define IDC_CREATEFANBUT                1009
#define IDC_CREATESTRIPBUT              1010
#define IDC_SCALEBUT                    1010
#define IDC_PLAYCAMBUT                  1010
#define IDC_XBUT                        1011
#define IDC_INTERPOLATEBUT              1011
#define IDC_YBUT                        1012
#define IDC_VIEW_FPSSPIN                1012
#define IDC_ZBUT                        1013
#define IDC_VIEW_FPSEDIT                1013
#define IDC_FLIPNORMALSBUT              1014
#define IDC_VIEW_FROMSPIN               1014
#define IDC_UNIFYNORMALSBUT             1015
#define IDC_VIEW_FROMEDIT               1015
#define IDC_TURNEDGEBUT                 1016
#define IDC_VIEW_TOSPIN                 1016
#define IDC_SUBDIVIDEBUT                1017
#define IDC_VIEW_TOEDIT                 1017
#define IDC_EXTUDEBUT                   1018
#define IDC_WELDBUT                     1019
#define IDC_MIRRORBUT                   1020
#define IDC_DELSELECTEDBUT              1021
#define IDC_MOD_FROMSPIN                1022
#define IDC_MOD_FROMEDIT                1023
#define IDC_MOD_TOSPIN                  1024
#define IDC_MOD_TOEDIT                  1025
#define IDC_EFFECTFRAMERANGECHECK       1026
#define IDC_BUTTONBONES                 1028
#define IDC_FITALLBUT                   1030
#define IDC_FITSELECTEDBUT              1031
#define IDC_PREVFRAMEBUT                1032
#define IDC_NEXTFRAMEBUT                1033
#define IDC_FRAMENAMEEDIT               1034
#define IDC_FRAMENUMEDIT                1035
#define IDC_TIMESCROLL                  1035
#define IDC_VERTEXMODEBUT               1036
#define IDC_FACEMODEBUT                 1037
#define IDC_BONEMODEBUT                 1038
#define IDC_OBJECTMODEBUT               1039
#define IDC_XEDIT                       1040
#define IDC_YEDIT                       1041
#define IDC_ZEDIT                       1042
#define IDC_FILEANDNUMBER_RADIO         1042
#define IDC_COUNTFEEDBACKEDIT           1043
#define IDC_FRAMENAME_RADIO             1043
#define IDC_CATEGORYCOMBO               1043
#define IDC_GRIDSIZEEDIT                1044
#define IDC_COMMANDLIST                 1044
#define IDC_PANVIEWSBUT                 1045
#define IDC_ASSIGNBUT                   1045
#define IDC_KEYEDIT                     1046
#define IDC_SHIFTCHECK                  1047
#define IDC_CTRLCHECK                   1048
#define IDC_ALTCHECK                    1049
#define IDC_PRESSKEYBUT                 1050
#define IDC_CURSHORTCUTEDIT             1052
#define IDC_USEDEDIT                    1053
#define IDC_WELDVERTSBUT                1054
#define IDC_DETACHBUT                   1055
#define IDC_DELETESELBUT                1056
#define IDC_SKINNUMEDIT                 1058
#define IDC_VERTSCROLL                  1060
#define IDC_HORIZSCROLL                 1061
#define IDC_ZOOMINBUT                   1062
#define IDC_ZOOMOUTBUT                  1063
#define IDC_NEXTSKINBUT                 1064
#define IDC_PREVSKINBUT                 1065
#define IDC_REPLACEVERTS_RADIO          1066
#define IDC_APPENDVERTS_RADIO           1067
#define IDC_ALIGNCHECK                  1068
#define IDC_BLENDEDIT                   1069
#define IDC_BLENDSPIN                   1070
#define IDC_STARTNUMEDIT                1073
#define IDC_STARTNAMEEDIT               1074
#define IDC_CHOOSESTARTBUT              1075
#define IDC_CHOOSEENDBUT                1076
#define IDC_ENDNUMEDIT                  1077
#define IDC_ENDNAMEEDIT                 1078
#define IDC_STARTFRAMESPIN              1079
#define IDC_ENDFRAMESPIN                1080
#define IDC_TARGETNUMEDIT               1081
#define IDC_OLDNAMEEDIT                 1082
#define IDC_FRAMELIST                   1082
#define IDC_TARGETNAMEEDIT              1082
#define IDC_NEWNAMEEDIT                 1083
#define IDC_BEFOREFIRSTCHECK            1083
#define IDC_CHOOSETARGETBUT             1083
#define IDC_AFTERFINALCHECK             1084
#define IDC_TARGETNUMSPIN               1084
#define IDC_AFTERFRAMECHECK             1085
#define IDC_FRAMENUMSPIN                1087
#define IDC_NEWFRAMENUMEDIT             1088
#define IDC_NEWFRAMENAMEEDIT            1089
#define IDC_BEFOREFRAMECHECK            1089
#define IDC_GPPOSEDIT                   1090
#define IDC_OUTPUTEDIT                  1091
#define IDC_INPUTEDIT                   1092
#define IDC_UEDIT                       1094
#define IDC_VEDIT                       1095
#define IDC_DRAWBUT                     1097
#define IDC_SIZEEDIT                    1098
#define IDC_SIZESPIN                    1099
#define IDC_SPRAYBUT                    1100
#define IDC_FILLBUT                     1101
#define IDC_SOFTEDIT                    1102
#define IDC_SOFTSPIN                    1103
#define IDC_FOREBUT                     1104
#define IDC_BACKBUT                     1105
#define IDC_COLORLISTBOX                1106
#define IDC_EXTRUDEEDIT                 1107
#define IDC_DRAWEFFECTCOMBO             1108
#define IDC_OPACITYSLIDER               1109
#define IDC_OPACITYEDIT                 1110
#define IDC_FADESLIDER                  1111
#define IDC_FADEEDIT                    1112
#define IDC_FADETOCOMBO                 1113
#define IDC_COMPOUNDCHECK               1114
#define IDC_FRONTRADIO                  1116
#define IDC_TOLERANCEEDIT               1117
#define IDC_TOLERANCESPIN               1118
#define IDC_MIRRORCHECK                 1119
#define IDC_OLDWIDTHEDIT                1120
#define IDC_OLDHEIGHTEDIT               1121
#define IDC_BEFOREFIRSTRADIO            1121
#define IDC_NEWWIDTHEDIT                1122
#define IDC_AFTERLASTRADIO              1122
#define IDC_RIGHTRADIO                  1123
#define IDC_NEWHEIGHTEDIT               1123
#define IDC_AFTERSKINRADIO              1123
#define IDC_TOPRADIO                    1124
#define IDC_INSERTAFTEREDIT             1124
#define IDC_INSERTAFTERSPIN             1125
#define IDC_PATHTREE                    1126
#define IDC_BACKRADIO                   1127
#define IDC_PATHEDIT                    1127
#define IDC_LEFTRADIO                   1128
#define IDC_COLORITEMLIST               1128
#define IDC_BOTTOMRADIO                 1129
#define IDC_OLDCOLORBUT                 1129
#define IDC_PALETTELIST                 1130
#define IDC_NEWCOLORBUT                 1131
#define IDC_CHOOSECOLORBUT              1132
#define IDC_APPLYBUT                    1133
#define IDC_XFORMGROUP                  1136
#define IDC_OXEDIT                      1138
#define IDC_OYEDIT                      1139
#define IDC_OZEDIT                      1140
#define IDC_SELECTIONCENTRECHECK        1141
#define IDC_SWAPCOLSBUT                 1142
#define IDC_UNDOMODE_TAB                1143
#define IDC_LIMITUNDOSCHECK             1144
#define IDC_MINUNDOSCHECK               1145
#define IDC_MAXUNDOSRADIO               1146
#define IDC_MAXUNDOSIZERADIO            1147
#define IDC_UNDOLEVELSEDIT              1149
#define IDC_MAXUNDOSIZEEDIT             1150
#define IDC_UNDOSIZEEDIT                1151
#define IDC_MAXUNDOSEDIT                1152
#define IDC_MINUNDOSEDIT                1153
#define IDC_MAXUNDOSIZESPIN             1154
#define IDC_MAXUNDOSSPIN                1157
#define IDC_MINUNDOSSPIN                1158
#define ID_FILE_SAVEAS                  32774
#define ID_FILE_MERGE                   32775
#define ID_FILE_CHOOSEREFERENCEMODEL    32777
#define ID_FILE_CLEARREFERENCEMODEL     32778
#define ID_FILE_EXIT                    32781
#define ID_EDIT_COPYSELECTED            32785
#define ID_EDIT_PASTETORANGE            32787
#define ID_EDIT_CHANGEFRAMENAME         32789
#define ID_EDIT_GOTOFRAME               32790
#define ID_EDIT_ADDNEWFRAME             32791
#define ID_EDIT_DELETECURRENTFRAME      32792
#define ID_EDIT_DELETEFRAMES            32793
#define ID_EDIT_MOVEFRAMES              32794
#define ID_EDIT_SELECTALL               32796
#define ID_EDIT_SELECTNONE              32797
#define ID_EDIT_SELECTINVERSE           32798
#define ID_EDIT_SELECTCONNECTED         32799
#define ID_EDIT_SELECTTOUCHING          32800
#define ID_VIEW_SKINS                   32801
#define ID_VIEW_SKINPAINTER             32802
#define ID_VIEW_MODELPROPERTIES         32804
#define ID_OPTIONS_VERTICESTICKS        32805
#define ID_OPTIONS_SHOWORIGIN           32806
#define ID_OPTIONS_SHOWGRID             32807
#define ID_OPTIONS_GROUNDPLANEPOSITION  32808
#define ID_OPTIONS_SYNCSKINSELECTION    32813
#define ID_OPTIONS_INCREASEGRIDSIZE     32815
#define ID_OPTIONS_DECREASEGRIDSIZE     32816
#define ID_OPTIONS_ZOOMIN               32818
#define ID_OPTIONS_ZOOMOUT              32819
#define ID_OPTIONS_CONFIGURE            32821
#define ID_TOOLS_GENERATEHEADERFILE     32822
#define ID_TOOLS_MEMOWINDOW             32823
#define ID_TOOLS_OUTPUTBOUNDINGBOX      32824
#define ID_TOOLS_NUMERICTYPEIN          32826
#define ID_TOOLS_SAVECAMERAANIMATION    32828
#define ID_FILE_IMPORT_IMPORTAPPENDVERTS 32840
#define ID_FILE_IMPORT_IMPORTAPPENDFRAMES 32841
#define ID_FILE_IMPORT_FRAMENAMESFROMTEXT 32842
#define ID_FILE_EXPORT_EXPORTTOMD2      32844
#define ID_FILE_EXPORT_EXPORTTOMDL      32845
#define ID_FILE_EXPORT_EXPORTFRAMETOASC 32846
#define ID_FILE_EXPORT_EXPORTMODELTOASC 32847
#define ID_FILE_EXPORT_EXPORTFRAMETO3DS 32848
#define ID_FILE_EXPORT_EXPORTMODELTO3DS 32849
#define ID_OPTIONS_SHOWNORMALS_NONE     32852
#define ID_OPTIONS_SHOWNORMALS_SELECTEDFACES 32853
#define ID_OPTIONS_SHOWNORMALS_ALL      32854
#define ID_OPTIONS_2DVIEW_DRAWBACKFACES 32855
#define ID_OPTIONS_2DVIEW_PLAYCAMERAXY  32857
#define ID_OPTIONS_2DVIEW_PLAYCAMERAXZ  32858
#define ID_OPTIONS_2DVIEW_PLAYCAMERAZY  32859
#define ID_OPTIONS_3DVIEW_WIREFRAME     32860
#define ID_OPTIONS_3DVIEW_FLATSHADED    32861
#define ID_OPTIONS_3DVIEW_GOURADSHADED  32862
#define ID_OPTIONS_3DVIEW_TEXTUREMAPPED 32863
#define ID_OPTIONS_3DVIEW_TEXTUREGOURAD 32864
#define ID_OPTIONS_3DVIEW_DRAWBACKFACES 32866
#define ID_OPTIONS_3DVIEW_SHOWREFERENCEMODEL 32867
#define ID_HELP_CONTENTS                32868
#define ID_HELP_KEYWORDSEARCH           32869
#define ID_HELP_ABOUT                   32871
#define ID_FILE_IMPORT_SKINIMAGE        32877
#define ID_FILE_IMPORT_SKINMESHFROMASC  32879
#define ID_FILE_EXPORT_CURRENTIMAGE_BMP 32880
#define ID_FILE_EXPORT_CURRENTIMAGE_PCX 32881
#define ID_FILE_EXPORT_SKINMESHTOASC    32883
#define ID_EDIT_GETPOSITIONFROMMODEL    32888
#define ID_EDIT_ADDNEWSKIN              32889
#define ID_EDIT_DELETECURRENTSKIN       32890
#define ID_EDIT_CLEARCURRENTSKIN        32891
#define ID_EDIT_RESIZESKIN              32892
#define ID_VIEW_3DEDITOR                32898
#define ID_OPTIONS_SYNC3DSELECTION      32903
#define ID_OPTIONS_KEEPWINDOWONTOP      32908
#define ID_OPTIONS_LINES_DONTDRAW       32909
#define ID_OPTIONS_LINES_NORMAL         32910
#define ID_OPTIONS_VERTICES_NONE        32911
#define ID_OPTIONS_VERTICES_DOTS        32912
#define ID_OPTIONS_VERTICES_TICKS       32914
#define ID_VIEW_SKINEDITOR              32928
#define ID_MRU1                         32930

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32931
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
